name: Code coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run coverage
        run: |
          git submodule update --init --recursive
          mvn clean test
          bash <(curl -s https://codecov.io/bash)