name: Java CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest, macOS-latest]
        java: [ '11' ]
      fail-fast: false
    name: JAVA ${{ matrix.java }} OS ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: build and run tests
        run: |
          git submodule update --init --recursive
          git apply catch_changes.patch
          mvn -q clean install -DskipTests -Dmaven.javadoc.skip=true
